<?php

/**
 * @author      Iwona Jóźwiak <advertcenter@gmail.com>
 * @package     DevVsAdmin\UIComponent
 * @date        2020
 * @copyright   Copyright (C) 2021 Advert Center
 * @license     See LICENSE_ADVERT_CENTER.txt for license details.
 */

/**
 * @var DevVsAdmin\SimpleModule\Block\Template $block
 */
?>


<h1>dev home</h1>
<h2><?php echo $this->getTemplateValue();?></h2>
<h2><?php echo get_class($block);?></h2>
