<?php

/**
 * @author      Iwona Jóźwiak <advertcenter@gmail.com>
 * @package     DevVsAdmin\UIComponent
 * @date        2020
 * @copyright   Copyright (C) 2021 Advert Center
 * @license     See LICENSE_ADVERT_CENTER.txt for license details.
 */

/**
 * @var Magento\Framework\View\Element\Template $block
 * @var DevVsAdmin\UIComponent\ViewModel\Home $viewModel
 */

$viewModel = $block->getViewModel();

?>

<div id="devVsAdmin-products" data-bind="scope: 'devvsadmin-products'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<div data-mage-init='{"collapsible":{"openedState": "active", "saveState": true}}'>
    <div data-role="title">
        Title
    </div>
    <div data-role="content">
        Collapsible content
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "devvsadmin-products": {
                    "component": "DevVsAdmin_UIComponent/js/home",
                    "data": <?php echo $viewModel->getJsonConfig(); ?>
                }
            }
        }

    }
}
</script>